Jcn 217 implementacion model
janis-commerce/mongodb-index-creator pull request #4
Opened 2020-01-14 13:43 UTC by Nataniel4

**JCN-217-IMPLEMENTACION-MODEL**
JCN-217 Optimizar y arreglar package mongodb-index-creator

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JCN-217

**DESCRIPCIÓN DEL REQUERIMIENTO**
Se requiere eliminar el uso del database-dispatcher y el package mongodb de forma directa y usar una instancia de Model en su lugar

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se desarrollaron los requerimientos solicitados

2020-01-14 21:21 UTC, gastonpereyra commented on lib/mongodb-index-creator.js
Estaría bueno ordenar las funciones de la clase, desde la "principal" arriba y las "internas" (en orden de ejecución" abajo, asi facilita la lectura del código.

2020-01-14 21:32 UTC, gastonpereyra requested changes
Hay un bug.

Cuando en la colección tengo un index que no esta definido en el schema, al intentar crear los indexes, se rompe con el error:

`index not found with name [INDEX_NAME]`

Lo que debería pasar es que ese index "extra" se droppee, y solo se creen (si es que es necesario) los que si estan definidos en el schema

2020-01-15 15:03 UTC, Nataniel4 commented
> Hay un bug.
> 
> Cuando en la colección tengo un index que no esta definido en el schema, al intentar crear los indexes, se rompe con el error:
> 
> `index not found with name [INDEX_NAME]`
> 
> Lo que debería pasar es que ese index "extra" se droppee, y solo se creen (si es que es necesario) los que si estan definidos en el schema

Solucionado!

2020-01-15 17:00 UTC, gastonpereyra commented on lib/helpers/indexes.js
> +		if(!isObject(clientSchemas)) {
Esta validación esta de más, ya que se hace dentro de `Collections.validate`.

2020-01-15 17:16 UTC, gastonpereyra reviewed
Sugiero que se ordenen TODOS los archivos con los métodos principales al principio y los auxiliares para facilitar la lectura.

También que si algunos métodos tienen JSDocs y otros no, que los que si tienen sean los métodos principales, ya que son los que se pueden usar "afuera", y no los auxiliares, como pasa en varios casos.

2020-01-15 17:46 UTC, gastonpereyra commented on lib/helpers/indexes.js
> +		return Object.entries(coreSchemas).reduce((prev, [databaseKey, collections]) => {
Sugerencia:

- En este método y en el que viene la parte donde se usa el `reduce` se parecen mucho.
- En el de clientes solo habría que formatear los clientes.

Entonces se podría crear una función para poder reutilizarla

Qué te parece ?

2020-01-15 20:58 UTC, gastonpereyra approved these changes

2020-01-15 22:28 UTC, juanhapes requested changes

2020-01-15 22:28 UTC, juanhapes commented on lib/mongodb-index-creator.js
> +			return Results.save('skipped', indexes.length);
Este `Results.save()` es 100% igual al de abajo, se debe hacer antes del `if()` asi se hace una vez sola, y si entra al `if()` hacer `return;` y listo

2020-01-15 22:28 UTC, juanhapes commented on lib/mongodb-index-creator.js
> +		const shouldUseReadDB = Settings.get('databaseReadType');
Esta solución no es correcta. Tranquilamente el servicio podría tener configurado el `databaseReadType` y ser el mismo el mismo type y mismo host, en ese caso no debería romper esta función.
La solución mas directa sin necesidad de comparar las configs de "read" y "write" es hacer 2 veces el `Promise.all()`, el 1ero para "write" y el 2do para "read". De esta forma, en caso de ser las mismas, cuando se realice el `_updateIndexes()` para "write" se realizarán las modificaiones y cuando se ejecute para "read" los _schemas_ van a ser iguales a los indices encontrados con el `getIndexes()

2020-01-15 22:28 UTC, juanhapes commented on lib/mongodb-index-creator.js
> +		const shouldUseReadDB = Settings.get('databaseReadType');
Se debe hacer un `await Promier.all()` y luego un `return Promise.all()`

2020-01-15 22:59 UTC, juanhapes requested changes

2020-01-15 22:59 UTC, juanhapes commented on lib/helpers/indexes.js
> +	static _generateModels(formattedIndexes, handler) {
En vez de `handler`podria ser `getModelInstance`

2020-01-15 22:59 UTC, juanhapes commented on lib/helpers/model.js
> +	static getInstanceByDatabaseKey(databaseKey, table) {
`getCoreInstance` me parece más correcto

2020-01-15 22:59 UTC, juanhapes commented on lib/helpers/model.js
> +	static getSessionInstance(client, table) {
`getClientInstance` me parece más correcto

2020-01-15 22:59 UTC, juanhapes commented on lib/helpers/model.js
> +'use strict';
Para mi este archivo se debe llamar `model-generator.js`

2020-01-16 16:57 UTC, merged