Jcn 256 ttl indexes serverless function
janis-commerce/mongodb-index-creator pull request #7
Opened 2020-04-29 14:25 UTC by maguimarijuan

**Link al ticket**
https://fizzmod.atlassian.net/browse/JCN-256
**Descripción del requerimiento**
Agregar soporte para índices TTL y un método para obtener la función serverless. 
**Descripción de la solución**
Se agregó el soporte del tipo de índices modificando el struct de lib/helpers/collection. También se agregó un getter para obtener las funciones serverless que se usaran en el serverless.js de cada servicio. 
**CHANGELOG**
- **changed**
- lib/mongodb-index-creator-test.js 
- test/mongodb-index-creator-test.js
- lib/helpers/collection.js

2020-04-29 21:23 UTC, Nataniel4 commented on README.md
> +				name: 'indicates-expiration'
Le falta la `,` despues del `name`, si hacemos copy/paste del ejemplo queda roto 😢

2020-04-30 14:18 UTC, juanhapes requested changes

2020-04-30 14:18 UTC, juanhapes commented on README.md
> +	package: {
Borremos `package` de este ejemplo, no suma nada

2020-05-08 15:04 UTC, Nataniel4 approved these changes

2020-05-08 15:27 UTC, merged